<template >
  <div class="content">
      <div class="welcome">
          <div class="welcome-words">
              <h1>Economic Simulator of Web3 Models</h1>
                <p>
                    We can give you a seamless experience of predicting economic trends
                </p>
                <p>
                in the future by analyzing an <strong style="color:#a9eff7;">economic model</strong>
                </p>
                <div class="welcome-btn">
                    <router-link to="/explore">
                        <el-button class="btn welcome-btn-explore">
                            Explore
                            <i class="el-icon-top-right"></i>
                        </el-button>
                    </router-link>
                    <router-link to="/create">
                        <el-button class="btn welcome-btn-create">
                            Create
                            <i class="el-icon-magic-stick"></i>
                        </el-button>
                    </router-link>
                </div>
          </div>
      </div>

      <div class="features-title">
          <h1>FEATURES</h1>
      </div>
      <div class="features-context">
          <el-carousel :interval="4000" type="card" height="300px">
            <el-carousel-item v-for="item in featuresBox" :key="item.id">
                <button>{{ item.id }}</button>
                <p>{{ item.context }}</p>
            </el-carousel-item>
        </el-carousel>
      </div>

      <div class="activeties-title">
        <h1>Awasome <span class="hightlight">Activities</span> You Can Do Here</h1>
      </div>
      <div class="activeties-context">
          <el-row :gutter="25">
            <el-col :span="4">
                <div class="grid-content bg-purple">
                    <img src="../assets/researcher.png" alt="researcher-icon" class="icon" />
                    <p class="participants">Researcher Guild</p>
                    <ul>
                        <li>Research common Web3 application modeling standards</li>
                        <li>Research new tracks and projects in the field of Web3</li>
                        <li>......</li>
                    </ul>
                </div>
            </el-col>

            <el-col :span="4">
                <div class="grid-content bg-purple">
                    <img src="../assets/developer.png" alt="developer-icon" class="icon" />
                    <p class="participants">Developer Guild</p>
                    <ul>
                        <li>Develop easy-to-use, beautiful, low-code Web3 application modeling tools</li>
                        <li>Develop tools required by other Guilds to form a self-contained tool chain</li>
                        <li>......</li>
                    </ul>
                </div>
            </el-col>

            <el-col :span="4">
                <div class="grid-content bg-purple">
                    <img src="../assets/producer.png" alt="producer-icon" class="icon" />
                    <p class="participants">Producer Guild</p>
                    <ul>
                        <li>Produce easy-to-understand, intuitive and multi-level Web3 application modeling results</li>
                        <li>Produce more diverse and rich Web3 domain knowledge</li>
                        <li>......</li>
                    </ul>
                </div>
            </el-col>

            <el-col :span="4">
                <div class="grid-content bg-purple">
                    <img src="../assets/business.png" alt="business-icon" class="icon" />
                    <p class="participants">Business Guild</p>
                    <ul>
                        <li>Transform the knowledge achievements generated by the community into commercial value</li>
                        <li>Explore more possible business models for the community</li>
                        <li>......</li>
                    </ul>
                </div>
            </el-col>

            <el-col :span="4">
                <div class="grid-content bg-purple">
                    <img src="../assets/evangelist.png" alt="evangelist-icon" class="icon" />
                    <p class="participants">Evangelist Guild</p>
                    <ul>
                        <li>Organize and participate in various publicity activities to help the community develop rapidly and expand its influence</li>
                        <li>Help newcomers quickly integrate into the community and gain a sense of belonging</li>
                        <li>......</li>
                    </ul>
                </div>
            </el-col>
          </el-row>
      </div>

      <div class="introduction">
          <div class="left">
              <span class="intro-right-context">How it Work </span>
              <i class="el-icon-right intro-right-context"></i>

          </div>
          <div class="right">
              <img src="../assets/introduction.png" alt="introduction" class="introduction" />
          </div>
      </div>

      <div class="roadmap">
          <div class="right">
              <i class="el-icon-back roadmap-right-context"></i>
              <span class="roadmap-right-context"> Road Map</span>
          </div>
          <div class="left">
              <el-timeline>
            <el-timeline-item
            v-for="(road, index) in roadMap"
            :key="index"
            :icon="road.icon"
            :type="road.type"
            :color="road.color"
            :size="road.size"
            :timestamp="road.timestamp">
            {{road.content}}
            </el-timeline-item>
        </el-timeline>
          </div>
      </div>

      <div class="invitation">
          <p class="bigger">Ready to build something <strong>epic</strong> ?</p>
          <p class="normal">You got this. And if not, we will help you get there!</p>
          <div class="invitation-btn">
              <router-link to="/create">
                <el-buttom class="btn btn-start">
                    Start Now
                    <i class="el-icon-magic-stick"></i>
                </el-buttom>
              </router-link>
              <el-buttom class="btn btn-learn">
                  Learn More
                  <i class="el-icon-reading"></i>
              </el-buttom>
          </div>
      </div>
      
      <div class="social-icon">
          <img src="../assets/discord.png" alt="discord-icon" class="discord-icon space" />
          <img src="../assets/twitter.png" alt="twitter-icon" class="icon space" />
          <img src="../assets/wechat.png" alt="wechat-icon" class="icon" />
      </div>
      <div class="copy-right">
          <span>&copy; Model Lab     |     Design:Model Lab</span>
      </div>
  </div>
</template>
<script>
export default {
  data() {
    return {
        featuresBox:[
            {id:1,context:"Domain-Specific Language (DSL) for designing tokenomics"},
            {id:2,context:"Visual modeling workspace with public models and private insights"},
            {id:3,context:"IST as the native NFT"},
            {id:4,context:"Ownership of an IST guarantees rights to (1) view insight metadata and (2) set price of it"},
            {id:5,context:"Incentives to dig out insights"},
            {id:6,context:"Trading royalty to creators of model and insight"},

        ],
        introBox:
          [
              {id:1,title:"Create",context:"Build an economy model"},
              {id:2,title:"Design",context:"Enter economy data for prediction"},
              {id:3,title:"Assume",context:"Write model properties based on assumptions"},
              {id:4,title:"Analyze",context:"Start model economy simulation"},
              {id:5,title:"Show",context:"View model's economy trend and properties check results"},
              {id:6,title:"Finish",context:"Publish model and insight to earn money"}
          ],
        roadMap:[{
          content: 'Set up community communication groups on Twitter and WeChat',
          timestamp: 'Jan, 2022',
          size: 'large',
          color:'rgb(123, 156, 56)',
        }, {
          content: 'Launched DeFi analysis tool DeFi UML',
          timestamp: 'May, 2022',
          //color: '#0bbd87'
          color:'rgb(123, 156, 56)',
        }, {
          content: 'Form a union on Discord and produce multiple DeFi modeling diagrams',
          color: 'smokewhite'
        }, {
          content: 'Publish ModelsDAO community website',
          color: '#smokewhite'
        }, {
          content: 'Launched DeFi Economic Model Simulation Tool ICOPlayGround',
          color: '#smokewhite'
        }, {
          content: 'Release Arweave-based community autonomy contract',
          color: '#smokewhite'
        }]
    };
  },
};
</script>
<style lang="scss" scoped>
.content{
    .welcome {
        text-align: center;
        margin-top: 0%;
        width: 100%;
        height: 560px;
        background-attachment: scroll, scroll, scroll, fixed;
		background-color: #645862;
		background-image: url("../assets/rainbowColor-small.png");
		background-position: bottom left, bottom right, top left, top center;
		background-repeat: no-repeat, no-repeat, repeat, no-repeat;
		background-size: cover, cover, cover, cover;
		color: #fff;
		cursor: default;
		padding: 6em 0;
        .welcome-words{
            color: #e2e4e4;
            margin-top: 120px;
            h1 {
                font-size:45px;
                font-weight:600;
            }
            p {
            font-size:22px;
            font-weight:550;
            margin-bottom: 0.5%;
            }
            .welcome-btn {
                margin-top: 5%;
                .btn {
                    color: white;
                    background: -webkit-linear-gradient(40deg, #8ee8f1, #b49af2);
                    border: none;
                    border-radius: 10px;
                    cursor: pointer;
                    width: 138px;
                    font-weight:bold;
                    font-size: 20px;
                }
                .welcome-btn-explore {
                    margin-right: 10%;
                    .el-icon-top-right {
                        margin-left: 8%;
                        font-size: 20px;
                    }
                }
                .welcome-btn-create {
                    .el-icon-magic-stick {
                        margin-left: 12%;
                        font-size: 20px;
                    }
                }
                .btn:hover {
                    background: -webkit-linear-gradient(40deg, #6be7f5, #9d79f1);
                }
            }    
        }
    }

    .features-title{
        font-size: 20px;
        background: -webkit-linear-gradient(top, #86f0f1, #b17feb);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        text-align: center; 
        margin-top: 6%;
    }
    .features-context {
        margin: 6% 15%;
        .el-carousel__item button {
            color: rgb(115, 193, 238);
            border-radius: 30px;
            border: none;
            background-color: #fdffff;
            width: 40px;
            height: 40px;
            margin-top: 10%;
            margin-left: 5%;
            font-size: 25px;
            font-weight: 800;
            text-align: center;
        }
        .el-carousel__item p {
            color: rgb(86, 144, 179);
            font-size: 25px;
            font-weight: 800;
            margin-left: 6%;
            margin-right: 6%;
            margin-top: 4%;
        }
        
        .el-carousel__item:nth-child(2n) {
            //background: -webkit-linear-gradient(40deg, #8ee8f1, #b49af2);
            background-image: linear-gradient(to left,#e0dcf8, #d0eafc);;
        }
        
        .el-carousel__item:nth-child(2n+1) {
            background: -webkit-linear-gradient(40deg, #d0f5fc, #e0dcf8);
        }
    }

    .activeties-title {
        font-size: 20px;
        background: -webkit-linear-gradient(top, #c0b1e5, #f56192);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        text-align: center; 
        margin-top: 10%;
        span {
            background:-webkit-linear-gradient(left, #f16aa9, #f19c6a);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
    }
    .activeties-context {
        margin: 5% 0%;
        padding-left: 15%;
        text-align: center;
        margin-bottom: 10%;
        width: 80%;
        .el-row {
            margin-bottom: 20px;
            &:last-child {
            margin-bottom: 0;
            }
        }
        .el-col {
            border-radius: 4px;
        }
        .bg-purple {
            border:solid #dbabc1 1px;
        }
        .bg-purple:hover {
            box-shadow: 0 0 4px #dbabc1;
        }
        .grid-content {
            border-radius: 4px;
            min-height: 330px;
            text-align: center;
            .icon {
                margin-top: 10%;
                height: 50px;
                width: 50px;
            }
            .participants {
                font-weight: 600;
                margin-top: 5%;
            }
            li {
                text-align: left;
                margin-bottom: 3%;
            }

        }
    }

    .introduction {
        width: 90%;
        margin-top: 5%;
        margin-left: 5%;
        .left {
            float: left;
            //background-color: yellowgreen;
            height: 50%;
            width: 30%;
            text-align: center;
            font-size: 23px;
            .intro-right-context {
                background: -webkit-linear-gradient(top, #636264, #b585f3);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                font-size: 50px;
                margin-top: 61%;
                margin-bottom: 61%;
            }
        }
        .right {
            float: right;
            height: 50%;
            width: 65%;
            img {
                width: 80%;
                height: 80%;
                margin-top: 0%;
            }
        }
    }

    .roadmap {
        width: 90%;
        margin-top: 55%;
        margin-bottom: 90%;
        margin-left: 5%;
        .left {
            float: left;
            background-color: rgb(213, 228, 184);
            height: 50%;
            width: 55%;
            .el-timeline {
                font-size: 20px;
                margin-left: 15%;
                margin-top: 5%;
            }
        }
        .right {
            float: right;
            //background-color: rgb(123, 156, 56);
            height: 50%;
            width: 32%;
            text-align: center;
            padding-right: 8%;
            .roadmap-right-context {
                background: -webkit-linear-gradient(top, #91bde6, #b2c790);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                font-size: 50px;
                margin-top: 31%;
                margin-bottom: 31%;
            }
        }
    }

    .invitation {
        margin-top: 1600px;
        background-image: linear-gradient(to left,rgb(172, 215, 238), rgb(230, 191, 238));
        height: 300px;
        margin-bottom: 100px;
        text-align: center;
        padding-top: 5%;
        p {
            color: white;
            margin-bottom: 2%;
        }
        .bigger {
            font-size: 40px;
        }
        .normal {
            font-size: 22px;
        }
        h6 {
            color:white;
            font-size: 20px;
        }
        .invitation-btn {
            margin-top: 50px;
            .btn {
                color: white;
                border: none;
                border-radius: 10px;
                cursor: pointer;
                padding: 0.5%;
                font-weight:bold;
                font-size: 22px;
                text-decoration: none;
            }
            .btn-start {
                background-color: rgb(170, 218, 241);
                margin-right: 100px;
            }
            .btn-start:hover {
                background-color: rgb(170, 195, 241);
            }
            .btn-learn:hover {
                color: rgb(245, 91, 245);
            }
            .router-link-active {
                text-decoration: none;
            }
            a {
                text-decoration: none;
            }
        }
        
    }

    .social-icon {
        text-align: center;
        margin-bottom: 40px;
        .icon {
            height: 30px;
            width: 30px;
        }
        .discord-icon {
            height: 27px;
            width: 27px;
        }
        .space {
            margin-right: 20px;
        }
    }
    .copy-right {
        text-align: center;
        margin-bottom: 200px;
    }

}
</style>